# Generated by Django 5.1.4 on 2025-01-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Login', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
            ],
        ),
    ]
